### ISSUE TITLE
NBA Team Box Scores: End of 2022-2023 Regular Season and Playoffs

### ISSUE THREAD

**Issue by larssoneg** [saiemgilani/hoopR-data#3]
Hi, Saiem and team! Excellent work with the hoopR package. I noticed that the timestamp for the NBA team box score data (hoopR::load_nba_team_box(seasons = hoopR::most_recent_nba_season()))  is 2023-04-03 17:35:13 EDT and does not include the last part of the 2022-23 regular season or the playoffs. Should these games be included at this point in time? Thanks!

**Comment by saiemgilani** [comment]
Update your package to the development version. This repository got too big and we had to move some stuff

```
remotes::install_github("sportsdataverse/hoopR")
```

**Comment by larssoneg** [comment]
Thanks for the quick reply. I am seeing the most recent games now. Keep up the great work!
